version: '3.7'

services: 
  mysql:
    container_name: dbsoesport
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "soesport"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - node_mods

  soeport:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm start 
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=mysql://root:root@dbsoesport/soesport
    networks:
      - node_mods
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mysql

networks:
  node_mods:
      name: node_mods

volumes:
  db_data:
  node_modules:
